import 'package:flutter/material.dart';

List<String> Branch_Data = [
  "Clear Selection",
  "Instrumentation Engineering",
  "Electronics Engineering",
  "Mechanical Engineering",
  "Artificial Intelligence and Data Science",
  "Oil and Paints Technology",
  "Electrical and Electronics Engineering",
  "Fibres and Textile Processing Technology",
  "Internet of Things (IoT)",
  "Paper and Pulp Technology",
  "Structural Engineering",
  "Electrical Engineering",
  "Food Technology",
  "Dyestuff Technology",
  "Automobile Engineering",
  "Mechatronics Engineering",
  "Aeronautical Engineering",
  "Computer Science and Information Technology",
  "Data Science",
  "Metallurgy and Material Technology",
  "Computer Science and Engineering (Artificial Intelligence)",
  "Printing Technology",
  "Computer Science and Engineering(Artificial Intelligence and Machine Learning)",
  "Electronics and Communication Engineering",
  "Computer Science and Engineering(Cyber Security)",
  "Textile Engineering (Fashion Technology)",
  "Production Engineering",
  "Surface Coating Technology",
  "Printing and Packing Technology",
  "Computer Science and Technology",
  "Paints Technology",
  "Mechanical Engineering[Sandwich]",
  "Oil,Oleochemicals and Surfactants Technology",
  "Cyber Security",
  "Artificial Intelligence and Machine Learning",
  "Oil Fats and Waxes Technology",
  "Textile Chemistry",
  "Information Technology",
  "Electronics and Telecommunication Engg",
  "Computer Science and Engineering(Data Science)",
  "Petro Chemical Technology",
  "Civil Engineering",
  "Petro Chemical Engineering",
  "Textile Technology",
  "Computer Science and Engineering",
  "Chemical Engineering",
  "Computer Engineering",
  "Electrical Engg[Electronics and Power]",
  "Pharmaceutical and Fine Chemical Technology",
  "Food Engineering and Technology",
  "Polymer Engineering and Technology",
  "Bio Medical Engineering",
  "Oil Technology",
  "Mechanical Engineering Automobile",
  "Production Engineering[Sandwich]",
  "Safety and Fire Engineering",
  "Data Engineering",
  "Industrial Engineering",
  "Bio Technology",
  "Textile Plant Engineering",
  "Agricultural Engineering",
  "Electrical Engg [Electrical and Power]",
  "Computer Science and Engineering (Internet of Things and Cyber Security Including Block Chain",
  "Electronics and Computer Science",
  "Plastic and Polymer Technology",
  "Mining Engineering",
  "Plastic Technology",
  "Man Made Textile Technology",
  "Civil and Environmental Engineering",
  "Plastic and Polymer Engineering",
  "Computer Technology",
  "Robotics and Automation",
  "Manufacturing Science and Engineering",
  "Pharmaceuticals Chemistry and Technology",
  "Artificial Intelligence",
  "Instrumentation and Control Engineering",
  "Silk Technology",
  "Civil and infrastructure Engineering",
  "Electronics and Computer Engineering",
  "Automation and Robotics",
  "Textile Engineering / Technology",
  "Robotics",
].toList();
