import 'package:flutter/material.dart';

List<String> College_Data = [
  "Clear Selection",
  "2146 - Adarsh Shikshan Prasarak Mandal's K. T. Patil College of Engineering and Technology, Osmanabad",
  "1123 - Dr.Rajendra Gode Institute of Technology & Research, Amravati",
  "1117 - Janata Shikshan Prasarak Mandalâ€™s Babasaheb Naik College Of Engineering, Pusad",
  "1012 - Government College of Engineering,Yavatmal",
  "1114 - Sipna Shikshan Prasarak Mandal College of Engineering & Technology, Amravati",
  "1180 - Sanmati Engineering College, Sawargaon Barde, Washim",
  "2020 - Shri Guru Gobind Singhji Institute of Engineering and Technology, Nanded",
  "2112 - Shree Yash Pratishthan, Shreeyash College of Engineering and Technology, Aurangabad",
  "3154 - Saraswati Education Society's Saraswati College of Engineering,Kharghar Navi Mumbai",
  "3199 - Shri Vile Parle Kelvani Mandal's Dwarkadas J. Sanghvi College of Engineering, Vile Parle,Mumbai",
  "3223 - Mahatma Education Society's Pillai HOC College of Engineering & Technology, Tal. Khalapur. Dist. Raigad",
  "3465 - Ideal Institute of Technology, Wada, Dist.Thane",
  "5107 - Shri Gulabrao Deokar College of Engineering, Jalgaon",
  "6122 - TSSMS's Pd. Vasantdada Patil Institute of Technology, Bavdhan, Pune",
  "6206 - Pune District Education Association's College of Engineering, Pune",
  "6319 - Shahajirao Patil Vikas Pratishthan, S.B.Patil College of Engineering, Vangali, Tal. Indapur",
  "6756 - Fabtech Technical Campus College of Engineering and Research, Sangola",
  "6757 - Yashoda Technical Campus, Wadhe, Satara.",
  "6794 - Anantrao Pawar College of Engineering & Research, Pune",
  "2141 - Shri Sai Samajik Vikas Santha's Shri Sai Colllege of Engineering, Paddari Village Tal. & Dist. Aurangabad",
  "1276 - Manav School of Engineering & Technology, Gut No. 1035 Nagpur Surat Highway, NH No. 6 Tal.Vyala, Balapur, Akola, 444302",
  "1105 - Prof. Ram Meghe Institute of Technology & Research, Amravati",
  "2516 - International Centre Of Excellence In Engineering and Management (ICEEM)",
  "2522 - STMEI's Sandipani Technical Campus-Faculty of Engineering, Latur.",
  "2573 - Gramin College of Engineering, Vishnupuri, Nanded",
  "3193 - Shivajirao S. Jondhale College of Engineering, Dombivali,Mumbai",
  "3204 - St. Francis Institute of Technology,Borivali, Mumbai",
  "3207 - Mahatma Education Society's Pillai College of Engineering, New Panvel",
  "3460 - Universal College of Engineering,Kaman Dist. Palghar",
  "4115 - Shri Ramdeobaba College of Engineering and Management, Nagpur",
  "4175 - JMSS Shri Shankarprasad Agnihotri College of Engineering, Wardha",
  "5164 - P.S.G.V.P. Mandal's D.N. Patel College of Engineering, Shahada, Dist. Nandurbar",
  "5303 - Hon. Shri. Babanrao Pachpute Vichardhara Trust, Group of Institutions (Integrated Campus)-Parikrama, Kashti Shrigondha,",
  "5331 - Sandip Foundation's, Sandip Institute of Engineering & Management, Nashik",
  "6156 - Marathwada Mitra Mandal's College of Engineering, Karvenagar, Pune",
  "6175 - Pimpri Chinchwad Education Trust, Pimpri Chinchwad College of Engineering, Pune",
  "6182 - Sinhgad Technical Education Society, Sinhgad Institute of Technology and Science, Narhe (Ambegaon)",
  "6271 - Pune Institute of Computer Technology, Dhankavdi, Pune",
  "6275 - Shivnagar Vidya Prasarak Mandal's College of Engineering, Malegaon-Baramati",
  "6277 - Dr. J. J. Magdum Charitable Trust's Dr. J.J. Magdum College of Engineering, Jaysingpur",
  "6326 - Shri Pandurang Pratishtan, Karmayogi Engineering College, Shelve, Pandharpur",
  "6545 - Samarth Education Trust's Arvind Gavali College Of Engineering Panwalewadi, Varye,Satara.",
  "6625 - Universal College of Engineering & Research, Sasewadi",
  "2127 - Mahatma Gandhi Missions College of Engineering, Hingoli Rd, Nanded.",
  "2137 - Nagnathappa Halge Engineering College, Parli, Beed",
  "3423 - Shree L.R. Tiwari College of Engineering, Mira Road, Mumbai",
  "3439 - Anjuman-I-Islam's Kalsekar Technical Campus, Panvel",
  "3440 - Metropolitan Institute of Technology & Management, Sukhalwad, Sindhudurg.",
  "3471 - New Horizon Institute of Technology & Management, Thane",
  "4147 - K.D.K. College of Engineering, Nagpur",
  "4302 - Gondia Education Society's Manoharbhai Patel Institute Of Engineering & Technology, Shahapur, Bhandara",
  "5162 - Amrutvahini Sheti & Shikshan Vikas Sanstha's Amrutvahini College of Engineering, Sangamner",
  "5382 - Ahmednagar Jilha Maratha Vidya Prasarak Samajache, Shri. Chhatrapati Shivaji Maharaj College of Engineering, Nepti",
  "5390 - K.V.N. Naik S. P. Sansth's Loknete Gopinathji Munde Institute of Engineering Education & Research, Nashik.",
  "6179 - Indira College of Engineering & Management, Pune",
  "6207 - Dr. D. Y. Patil Vidya Pratishthan Societyâ€™s Dr. D. Y. Patil Institute of Technology, Pimpri, Pune",
  "6281 - Modern Education Society's College of Engineering, Pune",
  "6283 - Annasaheb Dange College of Engineering and Technology, Ashta, Sangli",
  "6317 - Sharad Institute of Technology College of Engineering, Yadrav(Ichalkaranji)",
  "6643 - S K N Sinhgad College of Engineering, Korti Tal. Pandharpur Dist Solapur",
  "6758 - Sahyadri Valley College of Engineering & Technology, Rajuri, Pune.",
  "6772 - NBN Sinhgad Technical Institutes Campus, Pune",
  "6808 - Keystone School of Engineering, Pune",
  "1116 - Shri Shivaji Education Society's College of Engineering and Technology, Akola",
  "1126 - Shri. Dadasaheb Gawai Charitable Trust's Dr. Smt. Kamaltai Gawai Institute of Engineering & Technology, Darapur, Amravati",
  "1127 - Jagadambha Bahuuddeshiya Gramin Vikas Sanstha's Jagdambha College of Engineering and Technology, Yavatmal",
  "2250 - Aurangabad College of Engineering, Naygaon Savangi, Aurangabad",
  "3175 - M.G.M.'s College of Engineering and Technology, Kamothe, Navi Mumbai",
  "3210 - Excelsior Education Society's K.C. College of Engineering and Management Studies and Research, Kopri, Thane (E)",
  "3445 - Vishvatmak Jangli Maharaj Ashram Trust's Vishvatmak Om Gurudev College of Engineering, Mohili-Aghai, Shahpur.",
  "3447 - G.M.Vedak Institute of Technology, Tala, Raigad.",
  "4005 - Laxminarayan Institute of Technology, Nagpur",
  "4139 - Samridhi Sarwajanik Charitable Trust, Jhulelal Institute of Technology, Nagpur",
  "4188 - Krushi Jivan Vikas Pratishthan, Ballarpur Institute of Technology, Mouza Bamni",
  "4196 - Gurunanak Educational Society's Gurunanak Institute of Technology, Nagpur",
  "6004 - Government College of Engineering & Research, Avasari Khurd",
  "6178 - Sinhgad Technical Education Society's Smt. Kashibai Navale College of Engineering,Vadgaon,Pune",
  "6214 - K. E. Society's Rajarambapu Institute of Technology, Walwa, Sangli",
  "6273 - Bansilal Ramnath Agarawal Charitable Trust's Vishwakarma Institute of Technology, Bibwewadi, Pune",
  "6322 - Shree Gajanan Maharaj Shikshan Prasarak Manda'l Sharadchandra Pawar College of Engineering, Dumbarwadi",
  "6628 - Dattakala Group Of Institutions, Swami - Chincholi Tal. Daund Dist. Pune",
  "6754 - International Institute of Information Technology (IÂ²IT), Pune.",
  "6781 - Bhagwant Institute of Technology, Barshi",
  "6803 - Sant Gajanan Maharaj College of Engineering, Gadhinglaj",
  "6839 - Dr. D Y Patil Pratishthan's College of Engineering, Kolhapur",
  "3184 - Fr. Conceicao Rodrigues College of Engineering, Bandra,Mumbai",
  "3188 - Vasantdada Patil Pratishthan's College Of Engineering and Visual Arts, Sion, Mumbai",
  "3196 - Lokmanya Tilak College of Engineering, Kopar Khairane, Navi Mumbai",
  "3211 - S.I.E.S. Graduate School of Technology, Nerul, Navi Mumbai",
  "3224 - Leela Education Society, G.V. Acharya Institute of Engineering and Technology, Shelu, Karjat",
  "4004 - Government College of Engineering, Chandrapur",
  "4104 - Kavi Kulguru Institute of Technology & Science, Ramtek",
  "5124 - Jagadamba Education Soc. Nashik's S.N.D. College of Engineering & Reserch, Babulgaon",
  "6007 - Walchand College of Engineering, Sangli",
  "6155 - G.H.Raisoni College of Engineering & Management, Wagholi, Pune",
  "6223 - Pradnya Niketan Education Society's Nagesh Karajagi Orchid College of Engineering & Technology, Solapur",
  "6293 - Kai Amdar Bramhadevdada Mane Shikshan & Samajik Prathistan's Bramhadevdada Mane Institute of Technology, Solapur",
  "6304 - Loknete Hanumantrao Charitable Trust's Adarsh Institute of Technology and Research Centre, Vita,Sangli",
  "6768 - P.K. Technical Campus, Pune.",
  "6769 - Rasiklal M. Dhariwal Sinhgad Technical Institutes Campus, Warje, Pune.",
  "6786 - Dr. D. Y. Patil School of Engineering & Technology, Charholi(Bk), Via Lohgaon, Pune",
  "2113 - G. S. Mandal's Maharashtra Institute of Technology, Aurangabad",
  "2126 - Gramodyogik Shikshan Mandal's Marathwada Institute of Technology, Aurangabad",
  "2136 - Aditya Engineering College , Beed",
  "3146 - Jawahar Education Society's Annasaheb Chudaman Patil College of Engineering,Kharghar, Navi Mumbai",
  "3185 - Vivekanand Education Society's Institute of Technology, Chembur, Mumbai",
  "3187 - N.Y.S.S.'s Datta Meghe College of Engineering, Airoli, Navi Mumbai",
  "3200 - Hope Foundation and research center's Finolex Academy of Management and Technology, Ratnagiri",
  "3202 - Rajendra Mane College of Engineering & Technology Ambav Deorukh",
  "3203 - Atharva College of Engineering,Malad(West),Mumbai",
  "3214 - Xavier Institute Of Engineering C/O Xavier Technical Institute,Mahim,Mumbai",
  "3222 - Haji Jamaluddin Thim Trust's Theem College of Engineering, At. Villege Betegaon, Boisar",
  "3436 - B.R. Harne College of Engineering & Technology, Karav, Tal-Ambernath.",
  "3467 - Vishwaniketan's Institute of Management Entrepreneurship and Engineering Technology(i MEET), Khalapur Dist Raigad",
  "3475 - A. P. Shah Institute of Technology, Thane",
  "4648 - R.V. Parankar College of Engineering & Technology, Arvi, Dist Wardha",
  "5322 - Jamia Institute Of Engineering And Management Studies, Akkalkuwa",
  "6139 - Progressive Education Society's Modern College of Engineering, Pune",
  "6160 - JSPM's Imperial College of Engineering and Research, Wagholi, Pune",
  "6176 - G. H.Raisoni Institute of Engineering and Technology, Wagholi, Pune",
  "6288 - Bharati Vidyapeeth's College of Engineering, Kolhapur",
  "6308 - Shanti Education Society, A.G. Patil Institute of Technology, Soregaon, Solapur(North)",
  "6311 - Jayawant Shikshan Prasarak Mandal, Bhivarabai Sawant Institute of Technology & Research, Wagholi",
  "6635 - Samarth Group of Institutions, Bangarwadi, Post Belhe Tal. Junnar Dist. Pune",
  "3503 - Indala College Of Engineering, Bapsai Tal.Kalyan",
  "4116 - Ankush Shikshan Sanstha's G.H.Raisoni College of Engineering, Nagpur",
  "4145 - Wainganga College of Engineering and Management, Dongargaon, Nagpur",
  "4163 - Rajiv Gandhi College of Engineering Research & Technology Chandrapur",
  "4167 - Yeshwantrao Chavan College of Engineering,Wanadongri, Nagpur",
  "4174 - ST. Vincent Pallotti College of Engineering & Technology, Nagpur",
  "4613 - Suryodaya College of Engineering & Technology, Nagpur",
  "5139 - Pravara Rural College of Engineering, Loni, Pravaranagar, Ahmednagar.",
  "5177 - Matoshri College of Engineering and Research Centre, Eklahare, Nashik",
  "6220 - Shri Vithal Education and Research Institute's College of Engineering, Pandharpur",
  "6815 - Vidya Prasarini Sabha's College of Engineering & Technology, Lonavala",
  "2252 - Marathwada Shikshan Prasarak Mandal's Shri Shivaji Institute of Engineering and Management Studies, Parbhani",
  "3012 - Veermata Jijabai Technological Institute(VJTI), Matunga, Mumbai",
  "3217 - Vighnaharata Trust's Shivajirao S. Jondhale College of Engineering & Technology, Shahapur, Asangaon, Dist Thane",
  "3220 - Yadavrao Tasgaonkar College of Engineering & Management",
  "4649 - Bajaj Institute of Technology, Wardha",
  "5106 - Khandesh College Education Society's College Of Engineering And Management, Jalgaon",
  "5151 - MET Bhujbal Knowledge City MET League's Engineering College, Adgaon, Nashik.",
  "5160 - Sanjivani Rural Education Society's Sanjivani College of Engineering, Kopargaon",
  "5181 - Gokhale Education Society's, R.H. Sapat College of Engineering, Management Studies and Research, Nashik",
  "5330 - PUNE VIDYARTHI GRIHAâ€™S COLLEGE OF ENGINEERING & SHRIKRUSHNA S. DHAMANKAR INSTITUTE OF MANAGEMENT, NASHIK",
  "6028 - Department of Technology, Shivaji University, Kolhapur",
  "6141 - Jaywant Shikshan Prasarak Mandal's,Rajarshi Shahu College of Engineering, Tathawade, Pune",
  "6185 - Sinhagad Institute of Technology, Lonavala",
  "6203 - Marathwada Mitra Mandal's Institute of Technology, Lohgaon, Pune",
  "6217 - Shri. Balasaheb Mane Shikshan Prasarak Mandal's, Ashokrao Mane Group of Institutions",
  "6303 - Dr. Ashok Gujar Technical Institute's Dr. Daulatrao Aher College of Engineering, Karad",
  "6315 - Holy-Wood Academy's Sanjeevan Engineering and Technology Institute, Panhala",
  "6419 - Nutan College of Engineering and Research, Talegaon Dabhade Tal. Maval, Pune",
  "6767 - Suman Ramesh Tulsiani Technical Campus: Faculty of Engineering, Kamshet,Pune.",
  "6770 - SKN Sinhgad Institute of Technology & Science, Kusgaon(BK),Pune.",
  "6780 - D.Y.Patil Education Society's,D.Y.Patil Technical Campus, Faculty of Engineering & Faculty of Management,Talsande,Kolhapur.",
  "6822 - Pimpri Chinchwad Education Trust's Pimpri Chinchwad College Of Engineering And Research, Ravet",
  "3147 - Saraswati Education Society, Yadavrao Tasgaonkar Institute of Engineering & Technology, Karjat",
  "3183 - Anjuman-I-Islam's M.H. Saboo Siddik College of Engineering, Byculla, Mumbai",
  "3190 - Terna Engineering College, Nerul, Navi Mumbai",
  "3216 - Gharda Foundation's Gharda Institute of Technology,Khed, Ratnagiri",
  "3462 - VPM's Maharshi Parshuram College of Engineering, Velneshwar, Ratnagiri.",
  "4118 - Bapurao Deshmukh College of Engineering, Sevagram",
  "4142 - Ankush Shikshan Sanstha's G. H. Raisoni Institute of Engineering & Technology, Nagpur",
  "5169 - Nagaon Education Society's Gangamai College of Engineering, Nagaon, Tal Dist Dhule",
  "5173 - SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering, (Jain Gurukul), Neminagar,Chandwad,(Nashik)",
  "5418 - Guru Gobind Singh College of Engineering & Research Centre, Nashik.",
  "6184 - K. J.'s Educational Institut Trinity College of Engineering and Research, Pisoli, Haveli",
  "6222 - Dattajirao Kadam Technical Education Society's Textile & Engineering Institute, Ichalkaranji.",
  "6265 - Walchand Institute of Technology, Solapur",
  "6268 - Tatyasaheb Kore Institute of Engineering and Technology, Warananagar",
  "6282 - All India Shri Shivaji Memorial Society's Institute of Information Technology,Pune",
  "6325 - Alard Charitable Trust's Alard College of Engineering and Management, Pune",
  "6466 - Shree Santkrupa Shikshan Sanstha, Shree Santkrupa Institute Of Engineering & Technology, Karad",
  "6609 - Jaihind College Of Engineering,Kuran",
  "6759 - Shree Ramchandra College of Engineering, Lonikand,Pune",
  "6762 - Nanasaheb Mahadik College of Engineering,Walwa, Sangli.",
  "6797 - Dnyanshree Institute Engineering and Technology, Satara",
  "1005 - Sant Gadge Baba Amravati University,Amravati",
  "1002 - Government College of Engineering, Amravati",
  "1119 - Paramhansa Ramkrishna Maunibaba Shikshan Santha's , Anuradha Engineering College, Chikhali",
  "1128 - Prof Ram Meghe College of Engineering and Management, Badnera",
  "2111 - Everest Education Society, Group of Institutions (Integrated Campus), Ohar",
  "2134 - Peoples Education Society's College of Engineering, Aurangabad",
  "4137 - Sir Shantilal Badjate Charitable Trust's S. B. Jain Institute of technology, Management & Research, Nagpur",
  "5109 - Sandip Foundation, Sandip Institute of Technology and Research Centre, Mahiravani, Nashik",
  "6149 - Choudhary Attar Singh Yadav Memorial Trust,Siddhant College of Engineering, Maval",
  "6177 - Sinhgad College of Engineering, Vadgaon (BK), Pune",
  "6269 - Shetkari Shikshan Mandal's Pad. Vasantraodada Patil Institute of Technology, Budhgaon, Sangli",
  "6307 - Dhole Patil Education Society, Dhole Patil College of Engineering, Wagholi, Tal. Haveli",
  "6632 - Navsahyadri Education Society's Group of Institutions",
  "6634 - KJEI's Trinity Academy of Engineering, Yewalewadi, Pune",
  "6732 - Dr. D. Y. Patil School OF Engineering, Lohegaon, Pune",
  "6802 - Dr. D.Y.Patil Institute of Engineering, Management & Reseach, Akurdi, Pune",
  "2021 - University Department of Chemical Technology, Aurangabad",
  "2130 - Terna Public Charitable Trust's College of Engineering, Osmanabad",
  "2133 - Mahatma Basaweshwar Education Society's College of Engineering, Ambejogai",
  "2135 - Hi-Tech Institute of Technology, Aurangabad",
  "2533 - CSMSS Chh. Shahu College of Engineering, Aurangabad",
  "3014 - Sardar Patel College of Engineering, Andheri",
  "3212 - WATUMULL INSTITUTE OF ELECTRONICS ENGINEERING & COMPUTER TECHNOLOGY, ULHASNAGAR",
  "3215 - Bhartiya Vidya Bhavan's Sardar Patel Institute of Technology , Andheri, Mumbai",
  "3477 - Chhartrapati Shivaji Maharaj Institute of Technology, Shedung, Panvel",
  "4123 - Lokmanya Tilak Jankalyan Shikshan Sanstha, Priyadarshani College of Engineering, Nagpur",
  "4134 - Guru Nanak Institute of Engineering & Technology,Kalmeshwar, Nagpur",
  "4135 - Amar Seva Mandal's Shree Govindrao Vanjari College of Engineering & Technology, Nagpur",
  "4144 - Shri. Sai Shikshan Sanstha, Nagpur Institute of Technology, Nagpur",
  "4151 - Vidarbha Bahu-Uddeshiya Shikshan Sanstha's Tulshiramji Gaikwad Patil College of Engineering & Technology, Nagpur",
  "4193 - K.D.M. Education Society, Vidharbha Institute of Technology,Umred Road ,Nagpur",
  "4195 - Vidharbha Bahu uddeshiya Shikshan Sanstha's Abha Gaikwad â€“ Patil College of Engineering, Nagpur",
  "4285 - V M Institute of Engineering and Technology, Dongargaon, Nagpur",
  "5161 - Dr. Vithalrao Vikhe Patil College of Engineering, Ahmednagar",
  "5380 - Adsul's Technical Campus, Chas Dist. Ahmednagar",
  "6144 - Genba Sopanrao Moze College of Engineering, Baner-Balewadi, Pune",
  "6183 - Al-Ameen Educational and Medical Foundation, College of Engineering, Koregaon, Bhima",
  "6267 - Kolhapur Institute of Technology's College of Engineering(Autonomous), Kolhapur",
  "6313 - Jaywant College of Engineering & Polytechnic , Kille Macchindragad Tal. Walva District- Sangali",
  "6622 - ISBM College Of Engineering Pune",
  "6644 - Shri. Ambabai Talim Sanstha's Sanjay Bhokare Group of Institutes, Miraj",
  "6766 - Phaltan Education Society's College of Engineering Thakurki Tal- Phaltan Dist-Satara",
  "1268 - Siddhivinayak Technical Campus, School of Engineering & Research Technology, Shirasgon, Nile",
  "2129 - M.S. Bidve Engineering College, Latur",
  "3182 - Thadomal Shahani Engineering College, Bandra, Mumbai",
  "3189 - Bharati Vidyapeeth College of Engineering, Navi Mumbai",
  "3192 - Smt. Indira Gandhi College of Engineering, Navi Mumbai",
  "3194 - Vidyavardhini's College of Engineering and Technology, Vasai",
  "3198 - Konkan Gyanpeeth College of Engineering, Karjat",
  "3206 - S.S.P.M.'s College of Engineering, Kankavli",
  "3218 - Aldel Education Trust's St. John College of Engineering & Management, Vevoor, Palghar",
  "3221 - Late Shri. Vishnu Waman Thakur Charitable Trust, Viva Institute of Technology, Shirgaon",
  "4133 - Sanmarg Shikshan Sanstha's Smt. Radhikatai Pandav College of Engineering, Nagpur",
  "4136 - Lokmanya Tilak Jankalyan Shikshan Sastha, Priyadarshini J. L. College Of Engineering, Nagpur",
  "4141 - Shriram Gram Vikas Shikshan Sanstha, Vilasrao Deshmukh College of Engineering and Technology, Nagpur",
  "4190 - M.D. Yergude Memorial Shikshan Prasarak Mandal's Shri Sai College of Engineering & Technology, Badravati",
  "4192 - Maitraya Education Society, Nagarjuna Institute of Engineering Technology & Management, Nagpur",
  "4197 - Jai Mahakali Shikshan Sanstha, Agnihotri College of Engineering, Sindhi(Meghe)",
  "5004 - Government College of Engineering, Jalgaon",
  "5179 - Vishwabharati Academy's College of Engineering, Ahmednagar",
  "6187 - Sinhgad Academy of Engineering, Kondhwa (BK) Kondhwa-Saswad Road, Pune",
  "6274 - Pune Vidyarthi Griha's College of Engineering and Technology and G K Pate(Wani) Institute of Management, Pune",
  "6278 - All India Shri Shivaji Memorial Society's College of Engineering, Pune",
  "6649 - TSSM's Bhivarabai Sawant College of Engineering and Research, Narhe, Pune",
  "6755 - JSPM Narhe Technical Campus, Pune.",
  "6901 - MAEER's MIT College of Railway Engineering and Research, Jamgaon, Barshi",
  "1120 - Jawaharlal Darda Institute of Engineering and Technology, Yavatmal",
  "1130 - Vision Buldhana Educational & Welfare Society's Pankaj Laddhad Institute of Technology & Management Studies, Yelgaon",
  "3033 - Dr. Babasaheb Ambedkar Technological University, Lonere",
  "3201 - Rizvi Education Society's Rizvi College of Engineering, Bandra,Mumbai",
  "3219 - Koti Vidya Charitable Trust's Smt. Alamuri Ratnamala Institute of Engineering and Technology, Sapgaon, Tal. Shahapur",
  "4177 - Priyadarshini Bhagwati College of Engineering, Harpur Nagar, Umred Road,Nagpur",
  "5103 - Shri Shivaji Vidya Prasarak Sanstha's Late Bapusaheb Shivaji Rao Deore College of Engineering,Dhule",
  "5108 - Maratha Vidya Prasarak Samaj's Karmaveer Adv. Baburao Ganpatrao Thakare College Of Engineering, Nashik",
  "5121 - K. K. Wagh Institute of Engineering Education and Research, Nashik",
  "5409 - Rajiv Gandhi College of Engineering, At Post Karjule Hariya Tal.Parner, Dist.Ahmednagar",
  "6272 - Dr. D. Y. Patil Pratishthan's D.Y.Patil College of Engineering Akurdi, Pune",
  "6284 - Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering & Technology, Baramati Dist.Pune",
  "6289 - B.R.A.C.T's Vishwakarma Institute of Information Technology, Kondhwa (Bk.), Pune",
  "6310 - Nutan Maharashtra Vidya Prasarak Mandal, Nutan Maharashtra Institute of Engineering &Technology, Talegaon station, Pune",
  "6321 - Vidya Vikas Pratishthan Institute of Engineering and Technology, Solapur",
  "6795 - Shri.Someshwar Shikshan Prasarak Mandal, Sharadchandra Pawar College of Engineering & Technology, Someshwar Nagar",
  "6796 - Bharati Vidyapeeth's College of Engineering,Lavale, Pune",
  "1101 - Shri Sant Gajanan Maharaj College of Engineering,Shegaon",
  "1107 - P. R. Pote (Patil) Education & Welfare Trust's Group of Institution(Integrated Campus), Amravati",
  "1121 - Shri Hanuman Vyayam Prasarak Mandals College of Engineering & Technology, Amravati",
  "1125 - Dwarka Bahu Uddeshiya Gramin Vikas Foundation, Rajarshri Shahu College of Engineering, Buldhana",
  "2116 - Matoshri Pratishan's Group of Institutions (Integrated Campus), Kupsarwadi , Nanded",
  "2131 - Shree Tuljabhavani College of Engineering, Tuljapur",
  "2254 - Vilasrao Deshmukh Foundation Group of Institutions, Latur",
  "3139 - Vidyalankar Institute of Technology,Wadala, Mumbai",
  "3197 - Agnel Charities' FR. C. Rodrigues Institute of Technology, Vashi, Navi Mumbai",
  "3351 - Bharat College of Engineering, Kanhor, Badlapur(W)",
  "4179 - Lokmanya Tilak Jankalyan Shiksan Sanstha, Priyadarshini Indira Gandhi College of Engineering, Nagpur",
  "5104 - Shramsadhana Bombay Trust, College of Engineering & Technology, Jalgaon",
  "5130 - Brahma Valley College of Engineering & Research, Trimbakeshwar, Nashik",
  "5152 - G. H. Raisoni Institute of Business Management,Jalgaon",
  "5168 - T.M.E. Society's J.T.Mahajan College of Engineering, Faizpur",
  "5170 - Hindi Seva Mandal's Shri Sant Gadgebaba College of Engineering & Technology, Bhusawal",
  "5171 - Godavari Foundation's Godavari College Of Engineering, Jalgaon",
  "5182 - Kalyani Charitable Trust, Late Gambhirrao Natuba Sapkal College of Engineering, Anjaneri, Trimbakeshwar Road, Nashik",
  "5184 - Amruta Vaishnavi Education & Welfare Trust's Shatabdi Institute of Engineering & Research, Agaskhind Tal. Sinnar",
  "5381 - Shri. Jaykumar Rawal Institute of Technology, Dondaicha.",
  "5399 - Sanghavi College of Engineering, Varvandi, Nashik.",
  "5401 - Jawahar Education Society's Institute of Technology, Management & Research, Nashik.",
  "5408 - Vidya Niketan College of Engineering, Bota Sangamner",
  "5449 - Shri Vile Parle Kelavani Mandal's Institute of Technology, Dhule",
  "6005 - Government College of Engineering, Karad",
  "6145 - JSPM'S Jaywantrao Sawant College of Engineering,Pune",
  "6219 - KSGBS's Bharat- Ratna Indira Gandhi College of Engineering, Kegaon, Solapur",
  "6250 - D.Y. Patil College of Engineering and Technology, Kolhapur",
  "6320 - K.J.'s Educational Institute's K.J.College of Engineering & Management Research, Pisoli",
  "6640 - N. B. Navale Sinhgad College of Engineering, Kegaon, solapur",
  "6782 - Sahakar Maharshee Shankarrao Mohite Patil Institute of Technology & Research, Akluj",
  "1182 - Padmashri Dr. V.B. Kolte College of Engineering, Malkapur, Buldhana",
  "2008 - Government College of Engineering, Aurangabad",
  "2114 - Deogiri Institute of Engineering and Management Studies, Aurangabad",
  "2138 - Matsyodari Shikshan Sansatha's College of Engineering and Technology, Jalna",
  "3135 - Manjara Charitable Trust's Rajiv Gandhi Institute of Technology, Mumbai",
  "3148 - Mahavir Education Trust's Shah & Anchor Kutchhi Engineering College, Mumbai",
  "3176 - Thakur College of Engineering and Technology, Kandivali, Mumbai",
  "3353 - Dilkap Research Institute Of Engineering and Management Studies, At.Mamdapur, Post- Neral, Tal- Karjat, Mumbai",
  "4143 - Sanmarg Shikshan Sanstha, Mandukarrao Pandav College of Engineering, Bhandara",
  "4171 - Lokmanya Tilak Jankalyan Shikshan Sanstha's , Priyadarshini Institute of Engineering and Technology, Nagpur",
  "4181 - Swaminarayan Siddhanta Institute Of Technology, Nagpur",
  "5172 - R. C. Patel Institute of Technology, Shirpur",
  "6006 - College of Engineering, Pune",
  "6138 - Genba Sopanrao Moze Trust Parvatibai Genba Moze College of Engineering,Wagholi, Pune",
  "6146 - MIT Academy of Engineering,Alandi, Pune",
  "6270 - Rayat Shikshan Sanstha's Karmaveer Bhaurao Patil College of Engineering, Satara",
  "1265 - Mauli Group of Institutions, College of Engineering and Technology, Shegaon.",
  "3036 - Institute of Chemical Technology, Matunga, Mumbai",
  "3208 - Don Bosco Institute of Technology, Mumbai",
  "3209 - K J Somaiya Institute of Engineering and Information Technology, Sion, Mumbai",
  "4025 - Government College of Engineering, Nagpur",
  "4138 - Jaidev Education Society, J D College of Engineering and Management, Nagpur",
  "4172 - Anjuman College of Engineering & Technology, Nagpur",
  "5003 - University Institute of Chemical Technology, North Maharashtra University, Jalgaon",
  "5125 - Pravara Rural Education Society's Sir Visvesvaraya Institute of Technology, Chincholi Dist. Nashik",
  "5396 - College of Engineering and Technology ,North Maharashtra Knowledge City, Jalgaon",
  "5411 - Maulana Mukhtar Ahmad Nadvi Technical Campus, Malegaon.",
  "6298 - Zeal Education Society's Zeal College of Engineering & Reserch, Narhe, Pune",
  "6305 - S.D.N.C.R.E.S'S.Late Narayandas Bhawandas Chhabada Institute of Engineering & Technology, Satara",
  "6324 - Rajgad Dnyanpeeth's Technical Campus,Dhangwadi, Bhor",
  "6834 - Dr.D.Y.Patil College Of Engineering & Innovation,Talegaon",
  "6878 - Dr. A. D. Shinde College Of Engineering, Tal.Gadhinglaj, Kolhapur"
].toList();
